# syntax=docker/dockerfile:1.7
FROM node:20-alpine

WORKDIR /workspace
ARG CACHE_BUST=2
# 1) Copy only package manifests first (cache-friendly)
COPY frontend/package*.json frontend/

# 2) Install deps
RUN --mount=type=cache,target=/root/.npm \
    npm install --prefix frontend

# 3) Copy sources
COPY frontend/ frontend/

# 4) Dev env
ENV NODE_ENV=development \
    PORT=4000

# 5) Work from frontend dir and expose frontend port
WORKDIR /workspace/frontend
EXPOSE 4000

# CMD to run on start
CMD npm run start
